### ISSUE TITLE
Is it possible to enable TCP communication between two GPUs?

### ISSUE THREAD

**Issue by xcwanAndy** [czkkkkkk/gccl#2]
Hi, I saw that the default [dev_graph.json](https://github.com/czkkkkkk/gccl/blob/master/configs/dev_graph.json) can only enable inter-GPU communication within one host. Besides, the communication type can only support as much as IB_NET, i.e., GPUDirect RDMA.

Is it possible to run TCP communication between two GPUs in different hosts?

Hope you would give me some advice.

**Comment by czkkkkkk** [comment]
TCP connection is not enabled by default. You may need to change some source code to enable it. Specifically, [https://github.com/czkkkkkk/gccl/blob/153e8bf16dccfc0b91165ddb13e31eda36e1e28a/src/conn/connection.cc#L85](url) create IB connection for inter-machine communication by default, which is needed to change to `NET` connection. Then when creating the connection for `NET` in [https://github.com/czkkkkkk/gccl/blob/153e8bf16dccfc0b91165ddb13e31eda36e1e28a/src/conn/connection.cc#L101](url), creating a `NetConnection` should work for TCP communication.

**Comment by czkkkkkk** [comment]
Sorry there should be more changes. 

1. [https://github.com/czkkkkkk/gccl/blob/153e8bf16dccfc0b91165ddb13e31eda36e1e28a/src/conn/net.h#L76](url) should be uncommented.
2. [https://github.com/czkkkkkk/gccl/blob/153e8bf16dccfc0b91165ddb13e31eda36e1e28a/src/init.cc#L18](url) should change the `nullptr` to `gcclNetSocket`.

Supporting TCP connection is not well tested. Please feel free to contact me if you encounter any problem.

**Comment by xcwanAndy** [comment]
Thanks!
